version: '3'
services:

  mysql:
    image: mysql:5.6
    user: root
    privileged: true
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/work/mysqldata:/var/lib/mysql



  php5.5:
    image: bitnami/php-fpm:5.5.30-2
    user: root
    privileged: true
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ~/work/wwwroot/:/data/wwwroot/
      - ~/work/logs:/data/logs
    networks:
      - net-php5.5
      - net-mysql



  nginx:
    image: nginx
    user: root
    privileged: true
    volumes:
      - ~/work/wwwroot/:/data/wwwroot/
      - ~/work/wwwroot/nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/work/wwwroot/nginx_conf/conf.d:/etc/nginx/conf.d:ro
      - ~/work/logs:/data/logs
    command: [nginx-debug, '-g', 'daemon off;']
    restart: always
    networks:
      - net-php5.5
      - net-mysql
    ports:
      - 80:80
      - 3178:3178
      - 3179:3179


  redis:
    image: redis
    restart: always
    command: [redis-server]
    ports:
      - 6379:6379

networks:
  net-php5.5:
  net-mysql:
