mysql:
    image: mysql
    user: root
    privileged: true
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - /data/projects/mysqldata:/var/lib/mysql



php-fpm:
    image: bitnami/php-fpm:5.5.30-2
    user: root
    privileged: true

    ports:
        - 9000:9000
    volumes:
        - /data/projects/wwwroot/:/data/wwwroot/
        - /data/logs:/data/logs
        - /data/disk500/liaodong/soft/:/data/soft


web:
    image: nginx
    user: root
    privileged: true
    volumes:
        - /data/projects/wwwroot/:/data/wwwroot/
        - /data/projects/wwwroot/nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - /data/projects/wwwroot/nginx_conf/self:/etc/nginx/self:ro
        - /data/logs:/data/logs

    command: [nginx-debug, '-g', 'daemon off;']
    links:
        - "php-fpm"
        - "mysql"
    ports:
        - 80:80
