mysql:
    image: mysql
    user: root
    privileged: true
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ~/work/mysqldata:/var/lib/mysql



php-fpm:
    image: bitnami/php-fpm:5.5.30-2
    user: root
    privileged: true

    ports:
        - 9000:9000
    volumes:
        - ~/work/wwwroot/:/data/wwwroot/
        - ~/work/logs:/data/logs



web:
    image: nginx
    user: root
    privileged: true
    volumes:
        - ~/work/wwwroot/:/data/wwwroot/
        - ~/work/wwwroot/nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ~/work/wwwroot/nginx_conf/self:/etc/nginx/self:ro
        - ~/work/logs:/data/logs

    command: [nginx-debug, '-g', 'daemon off;']
    links:
        - "php-fpm"
        - "mysql"
    ports:
        - 80:80
