version: '3'
services:

  mysql:
    image: mysql:5.6
    user: root
    privileged: true
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - D:/mysqldata:/var/lib/mysql


  redis:
    image: redis
    restart: always
    command: [redis-server]
    ports:
      - 6379:6379
